Feature/sid 168 send token button alway active show error message if needed
TDSoftware/subidentity-webapp pull request #114
Opened 2022-07-15 17:01 UTC by sosan-neikbeen

2022-07-20 07:08 UTC, dobschal requested changes
The toast looks nice.

2022-07-20 07:08 UTC, dobschal commented on src/components/partials/profile/ProfileHeader.vue
> +                "Add wallet connection with Polkadot.js extension to use this feature"
@sosan-neikbeen Please use the following text:
```
To use this feature, please attach a wallet connection with polkadot{.js} extension. Click here for more help.
```

Is it possible to have a link in the toast? 

Would be nice to redirect to: https://parallelfi.gitbook.io/parallel-finance/polkadot-network/parallel-product-guides/a-guide-to-testnet/polkadot-.js-connect-wallet

2022-07-21 08:54 UTC, dobschal requested changes

2022-07-21 08:54 UTC, dobschal commented on src/components/partials/profile/ProfileHeader.vue
> +            href: "https://parallelfi.gitbook.io/parallel-finance/polkadot-network/parallel-product-guides/a-guide-to-testnet/polkadot-.js-connect-wallet",
add ```target="_blank"``` please

2022-07-21 10:20 UTC, sosan-neikbeen commented
https://user-images.githubusercontent.com/95384931/180190737-f978f495-bb31-4c62-915b-98b29cd58be6.mp4

Toast message example when no web3 account is found

2022-08-18 09:25 UTC, dobschal approved these changes

2022-08-18 09:25 UTC, merged