fix mobile header text
TDSoftware/subidentity-webapp pull request #54
Opened 2022-05-23 15:15 UTC by sosan-neikbeen

2022-05-24 06:23 UTC, dobschal requested changes

2022-05-24 06:23 UTC, dobschal commented on src/components/layouts/SecondaryLayout.vue
> +    <Header :titel="$route.path === '/search' ? 'Search' : 'Profile'" />
@sosan-neikbeen typo:  ```titel``` --> ```title```

2022-05-24 06:23 UTC, dobschal commented on src/components/partials/general/Header.vue
> +        titel: {
same here. ```title```

2022-05-25 06:21 UTC, a-oertel approved these changes

2022-05-27 07:55 UTC, merged