show error message for invalid custom node address
TDSoftware/subidentity-webapp pull request #55
Opened 2022-05-23 15:17 UTC by sosan-neikbeen

2022-05-24 06:28 UTC, dobschal requested changes

2022-05-24 06:28 UTC, dobschal commented on src/components/partials/IdentitySearch/CustomNodeModal.vue
> +                this.busy = false;
@sosan-neikbeen put the ```this.busy = false;``` in a ```finally``` block instead writing it twice.

2022-05-24 06:28 UTC, dobschal commented on src/components/partials/IdentitySearch/CustomNodeModal.vue
> +            }
@sosan-neikbeen a bit late for an early exit :D Nice, but use a standard if/else statement here.

2022-05-27 07:48 UTC, a-oertel commented on src/components/partials/IdentitySearch/CustomNodeModal.vue
> +            }
couldn't you write that like:
```
if(e.message === "InvalidAddressError") this.error = "The address is invalid. It should start with 'wss://'.";
else this.error = "Could not reach your entered address. Please check again and enter a valid address.";
```

2022-05-27 07:52 UTC, a-oertel commented on src/components/partials/IdentitySearch/CustomNodeModal.vue
> +        return this.newCustomNodeAddress.startsWith("wss://");
Could you please also add a check for ws:// and allow that? The error message and placeholder can stay as is.

2022-05-27 07:52 UTC, a-oertel commented on src/components/partials/IdentitySearch/CustomNodeModal.vue
> +        return this.newCustomNodeAddress.startsWith("wss://");
Could you please also add a check for ws:// and allow that? The error message and placeholder can stay as is.

2022-05-30 13:13 UTC, a-oertel approved these changes

2022-05-30 13:14 UTC, merged